prepare:
  fetch:
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/phpcodesniffer.xml"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/phpmd.xml"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/.scss-lint.yml"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/.eslintignore"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/.eslintrc.js"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/tslint.json"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
      - php:
      - python:
  eslint:
    enabled: true
    # 5.7.0
    channel: "eslint-5"
  tslint:
    enabled: true
    # 5.9.1
    config: tslint.json
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "phpcodesniffer.xml"
      ignore_warnings: false
      encoding: utf-8
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
  scss-lint:
    enabled: true
exclude_patterns:
   - "**/vendor/"
