prepare:
  fetch:
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/phpcodesniffer.xml"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/phpmd.xml"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/.scss-lint.yml"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/.eslintignore"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/.eslintrc.js"
  - "https://raw.githubusercontent.com/studyportals/CodeStyle/master/tslint.json"
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
      - php:
      - python:
  eslint:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "phpcodesniffer.xml"
      ignore_warnings: false
      encoding: utf-8
    checks:
      Squiz Commenting ClassComment Missing:
        enabled: false
      Squiz Commenting VariableComment Missing:
        enabled: false
      Squiz Commenting FunctionComment Missing:
        enabled: false
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
  scss-lint:
    enabled: true
ratings:
  paths:
    - "**.php"
    - "**.scss"
    - "**.js"
exclude_paths:
   - "**/vendor/"
