#https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

linters:
  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: ^[a-zA-Z]*-?[a-zA-Z]*$
    convention_explanation: "UpperCamelCase"
    function_convention: ^[a-zA-Z]*-?[a-zA-Z]*$
    function_convention_explanation: "Only letters allowed"
    mixin_convention: ^[a-zA-Z]+$
    mixin_convention_explanation: "Only letters allowed"
    variable_convention: ^[A-Z][a-zA-Z]*$
    variable_convention_explanation: "UpperCamelCase"

  SelectorFormat:
    enabled: true
    allow_leading_underscore: false
    convention: ^[a-zA-Z]*-?[a-zA-Z]*$
    convention_explanation: "SMACSS compliance"
    element_convention: ^[a-zA-Z]+\d?$
    element_convention_explanation: "Only letters allowed"
    id_convention: ^[a-zA-Z]+$
    id_convention_explanation: "Only letters allowed"
    attribute_convention: ^[a-z]+$
    attribute_convention_explanation: "Lowercase only"

  NestingDepth:
    enabled: true
    max_depth: 4
  #"max-nesting-depth": 4

  LeadingZero:
    enabled: true
    style: include_zero
  #"number-leading-zero": "always"

  Indentation:
    enabled: true
    character: tab
    width: 1
  #"indentation": "tab"

  SpaceBetweenParens:
    enabled: true
    spaces: 0
  #"function-parentheses-space-inside": "never"

  IdSelector:
    enabled: false
  #"selector-max-id": 0   NOT SURE

  SpaceBeforeBrace:
    enabled: false
  #"block-closing-brace-space-after": "never"

  Shorthand:
    enabled: false
  #"shorthand-property-no-redundant-values": true

  EmptyLineBetweenBlocks:
    enabled: true
  #"rule-empty-line-before": true
  #"block-opening-brace-newline-after": "always"
  #"block-closing-brace-newline-after": "always",

  Comment:
    enabled: false
  #

  PropertySortOrder:
    enabled: false
  #

  FinalNewline:
    enabled: true
    present: false
  #"no-missing-end-of-source-newline": true

  HexNotation:
    enabled: true
    style: uppercase
  #"color-hex-case": "upper"

  HexLength:
    enabled: true
    style: long
  #"color-hex-length": "long"

  HexValidation:
    enabled: true
  #"color-no-invalid-hex": true

  SingleLinePerSelector:
    enabled: false
  #"selector-list-comma-newline-after" : "always"

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
